In [25]:
import os
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, text, inspect
import psycopg2
from dotenv import load_dotenv

load_dotenv()  

PG_HOST = os.environ['POSTGRES_HOST']
PG_PORT = os.environ.get('POSTGRES_PORT', '5432')
PG_DB = os.environ['POSTGRES_DB']
PG_USER = os.environ['POSTGRES_USER']
PG_PASS = os.environ['POSTGRES_PASSWORD']

In [26]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine.url import URL

def get_engine(
    user: str, password: str, host: str, port: int, dbname: str,
    pool_size: int = 5, max_overflow: int = 10, pool_timeout: int = 30
):
    url = URL.create(
        drivername="postgresql+psycopg2",
        username=user,
        password=password,
        host=host,
        port=port,
        database=dbname
    )
    engine = create_engine(
        url,
        pool_size=pool_size,
        max_overflow=max_overflow,
        pool_timeout=pool_timeout,
        future=True # nutze moderne SQLAlchemy APIs
    )
    return engine

engine = get_engine(PG_USER, PG_PASS, PG_HOST, int(PG_PORT), PG_DB)

In [27]:
with engine.connect() as conn:
    res = conn.execute(text("SELECT 1"))
    print(res.scalar())  # sollte 1 ausgeben

1

In [28]:
def read_table_to_df(sql: str, engine):
    with engine.connect() as conn:
        return pd.read_sql(sql, conn)

df = read_table_to_df("SELECT * FROM bank_customers;", engine)
print(df.shape)
df.head()
type(df)

(10000, 12)

pandas.core.frame.DataFrame

In [29]:
def format_balances(balances):
    formated_balances = pd.cut(balances, bins=10, labels=[f"Balance_Cluster_{i}" for i in range(1, 11)])
    return formated_balances

def format_ages(ages):
    bins = [17, 30, 45, 55, 65, 100]  
    labels = [
        'Age_Young_Adults',           #(18-29)
        'Age_Adults_in_their_Prime',  #(30-44)
        'Age_Middle_aged',            #(45-54)
        'Age_Pre_retirees',           #(55-64)
        'Age_Young_Seniors'           #(65-77)
    ]
    
    formated_ages = pd.cut(ages, bins=bins, labels=labels, right=False)
    return formated_ages

def format_salaries(salaries):
    bins = [0.0, 1000.0, 10000.0, 30000.0, 60000.0, 100000.0, 150000.0, 200000.0]
    labels = [
        'Salarie_Very_low',       # (0-1k)
        'Salarie_Low',            # (1k-10k)
        'Salarie_Below_average',  # (10k-30k)
        'Salarie_Average',        # (30k-60k)
        'Salarie_Above_average',  # (60k-100k)
        'Salarie_High',           # (100k-150k)
        'Salarie_Very_high'       # (150k-200k)
    ]
    
    formatted_salaries = pd.cut(salaries, bins=bins, labels=labels, right=False)
    return formatted_salaries

def format_credit_scores(credit_scores):
    bins = [0, 580, 670, 740, 800, 851]
    labels = [
        'Credit_Score_Poor',               # 300-579
        'Credit_Score_Fair',               # 580-669
        'Credit_Score_Good',               # 670-739
        'Credit_Score_Very_Good',          # 740-799
        'Credit_Score_Excellent'           # 800-850
    ]
    
    formatted_credit_scores = pd.cut(credit_scores, bins=bins, labels=labels, right=False)
    return formatted_credit_scores

def format_tenures(tenures):
    formated_tenures = "Tenure_" + tenures.astype(str)
    return formated_tenures

In [30]:
df_formated = df.assign(
    customer_id=df['customer_id'], #Nicht nötig, wenn churn propensity gesucht ist.
    credit_score=format_credit_scores(df['credit_score']),
    country=df['country'],
    gender=df['gender'],
    age=format_ages(df['age']),
    tenure=format_tenures(df['tenure']),
    balance=format_balances(df['balance']),
    products_number=df['products_number'],
    credit_card=df['credit_card'],
    active_member=df['active_member'],
    estimated_salary=format_salaries(df['estimated_salary']),
    churn=df['churn']
)


df_formated['gender'] = 'Gender_' + df_formated['gender']
df_formated['country'] = 'Country_' + df_formated['country']
df_formated['products_number'] = 'ProductsNumber_' + df_formated['products_number'].astype(str)
df_formated['credit_card'] = df_formated['credit_card'].map({1:'CreditCard_Yes', 0:'CreditCard_No'})
df_formated['active_member'] = df_formated['active_member'].map({1:'ActiveMember_Yes', 0:'ActiveMember_No'})
df_formated['churn'] = df_formated['churn'].map({1:'Churn_Yes', 0:'Churn_No'})
  
df_formated = df_formated.drop(columns=['customer_id'])#Nicht nötig, wenn churn propensity gesucht ist.

df_formated['key'] = ['key_' + str(i) for i in df_formated.index]


df_formated.head()

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,key
0,Credit_Score_Fair,Country_France,Gender_Female,Age_Adults_in_their_Prime,Tenure_2,Balance_Cluster_1,ProductsNumber_1,CreditCard_Yes,ActiveMember_Yes,Salarie_High,Churn_Yes,key_0
1,Credit_Score_Fair,Country_Spain,Gender_Female,Age_Adults_in_their_Prime,Tenure_1,Balance_Cluster_4,ProductsNumber_1,CreditCard_No,ActiveMember_Yes,Salarie_High,Churn_No,key_1
2,Credit_Score_Poor,Country_France,Gender_Female,Age_Adults_in_their_Prime,Tenure_8,Balance_Cluster_7,ProductsNumber_3,CreditCard_Yes,ActiveMember_No,Salarie_High,Churn_Yes,key_2
3,Credit_Score_Good,Country_France,Gender_Female,Age_Adults_in_their_Prime,Tenure_1,Balance_Cluster_1,ProductsNumber_2,CreditCard_No,ActiveMember_No,Salarie_Above_average,Churn_No,key_3
4,Credit_Score_Excellent,Country_Spain,Gender_Female,Age_Adults_in_their_Prime,Tenure_2,Balance_Cluster_6,ProductsNumber_1,CreditCard_Yes,ActiveMember_Yes,Salarie_Above_average,Churn_No,key_4

In [31]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
#Einführen eines Schlüssels.
df_with_keys = df_formated.copy()

interval = 2  
cols = list(df_with_keys.columns)
new_cols = []
key_counter = 1

for i, col in enumerate(cols, start=1):
    if (i - 1) % interval == 0:
        key_name = f'key{key_counter}'
        df_with_keys[key_name] = ['key_' + str(j+1) for j in range(len(df))]
        new_cols.append(key_name)
        key_counter += 1
    new_cols.append(col)

df_with_keys = df_with_keys[new_cols]

df_with_keys.head()

,key1,credit_score,country,key2,gender,age,key3,tenure,balance,key4,products_number,credit_card,key5,active_member,estimated_salary,key6,churn,key
0,key_1,Credit_Score_Fair,Country_France,key_1,Gender_Female,Age_Adults_in_their_Prime,key_1,Tenure_2,Balance_Cluster_1,key_1,ProductsNumber_1,CreditCard_Yes,key_1,ActiveMember_Yes,Salarie_High,key_1,Churn_Yes,key_0
1,key_2,Credit_Score_Fair,Country_Spain,key_2,Gender_Female,Age_Adults_in_their_Prime,key_2,Tenure_1,Balance_Cluster_4,key_2,ProductsNumber_1,CreditCard_No,key_2,ActiveMember_Yes,Salarie_High,key_2,Churn_No,key_1
2,key_3,Credit_Score_Poor,Country_France,key_3,Gender_Female,Age_Adults_in_their_Prime,key_3,Tenure_8,Balance_Cluster_7,key_3,ProductsNumber_3,CreditCard_Yes,key_3,ActiveMember_No,Salarie_High,key_3,Churn_Yes,key_2
3,key_4,Credit_Score_Good,Country_France,key_4,Gender_Female,Age_Adults_in_their_Prime,key_4,Tenure_1,Balance_Cluster_1,key_4,ProductsNumber_2,CreditCard_No,key_4,ActiveMember_No,Salarie_Above_average,key_4,Churn_No,key_3
4,key_5,Credit_Score_Excellent,Country_Spain,key_5,Gender_Female,Age_Adults_in_their_Prime,key_5,Tenure_2,Balance_Cluster_6,key_5,ProductsNumber_1,CreditCard_Yes,key_5,ActiveMember_Yes,Salarie_Above_average,key_5,Churn_No,key_4

In [33]:
textified_data = df_with_keys.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
textified_data.head

<bound method NDFrame.head of 0       key_1 Credit_Score_Fair Country_France key_1 G...
1       key_2 Credit_Score_Fair Country_Spain key_2 Ge...
2       key_3 Credit_Score_Poor Country_France key_3 G...
3       key_4 Credit_Score_Good Country_France key_4 G...
4       key_5 Credit_Score_Excellent Country_Spain key...
                              ...
9995    key_9996 Credit_Score_Very_Good Country_France...
9996    key_9997 Credit_Score_Poor Country_France key_...
9997    key_9998 Credit_Score_Good Country_France key_...
9998    key_9999 Credit_Score_Very_Good Country_German...
9999    key_10000 Credit_Score_Very_Good Country_Franc...
Length: 10000, dtype: object>

In [36]:
#Building sentences 

number_of_replication = 20  
key_counter = 1

df_with_keys = df_with_keys[new_cols]

df_with_keys.head()

senteces = textified_data.copy()
index = 0
for val in ed1.tolist():
    i = 0
    while i < 19:
        senteces.iloc[index] = [senteces.iloc[index] + row]
        i += 1
    index += 1
print(senteces.head)

AttributeError: 'Series' object has no attribute 'iterrows'